name: Labby
options:
  bundleIdPrefix: com.inverse
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "592B8GFT9Q"
    CODE_SIGN_STYLE: Automatic

packages:
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup.git
    from: "2.6.0"

targets:
  Labby:
    type: application
    platform: iOS
    sources:
      - path: Labby
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: SwiftSoup
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Labby/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.inverse.labby
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
    info:
      path: Labby/Info.plist
      properties:
        CFBundleDisplayName: Labby
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true

  LabbyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LabbyTests
    dependencies:
      - target: Labby
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.inverse.labby.tests

schemes:
  Labby:
    build:
      targets:
        Labby: all
        LabbyTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - LabbyTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
