name: HomeLabHub
options:
  bundleIdPrefix: com.homelabhub
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

packages:
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup.git
    from: "2.6.0"

targets:
  HomeLabHub:
    type: application
    platform: iOS
    sources:
      - path: HomeLabHub
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: SwiftSoup
    settings:
      base:
        INFOPLIST_FILE: HomeLabHub/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.homelabhub.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
    info:
      path: HomeLabHub/Info.plist
      properties:
        CFBundleDisplayName: HomeLabHub
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
          NSAllowsLocalNetworking: true

  HomeLabHubTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: HomeLabHubTests
    dependencies:
      - target: HomeLabHub
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.homelabhub.app.tests

schemes:
  HomeLabHub:
    build:
      targets:
        HomeLabHub: all
        HomeLabHubTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - HomeLabHubTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
